# Generated by Django 4.2.10 on 2024-02-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('recruiter', 'Recruiter')], default='seeker', max_length=10),
        ),
    ]
