# Generated by Django 4.2.10 on 2024-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
