# Generated by Django 4.2.10 on 2024-02-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='name',
        ),
    ]
