version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: jobless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes: 
      - .:/usr/src/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
