# Generated by Django 4.2.10 on 2024-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
