# Generated by Django 4.2.10 on 2024-03-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_files_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='type',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='mimetype',
            field=models.CharField(default='pdf', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
